### ISSUE TITLE
503 非法请求

### ISSUE THREAD

**Issue by rvnox** [w303972870/ucore#1]
在配置文件需要额外配置嘛，提示503非法请求

[ucore]
daemon = False #daemon方式后台运行，默认true
port = 80      #监听端口，默认80
host = 192.168.112.128  #监听ip，默认为空(监听的时候“:port”)

[log]
dir = /data/logs/ #日志目录
logname = access-ucore.log #日志名称，默认access-ucore.log

[ldap]
host = 10.64.100.1
port = 389 # 默认389
uid = cn # 默认cn
bind_dn = CN=Administrator,CN=Users,DC=zgtest,DC=local
password = Admin123

[platform]
platform = cmdp,workcenter # 支持验证的平台标识，所有的验证都包含这个
platform_key = staffAccess # 包含验证的平台标识的ldap中的key，即Ldap中的过滤规则：($platform_key=$platform)，请求url会包含$platform，登录验证时用到
ips = 192.168.112.128  # 求白名单,不在白名单的禁止请求

[cmdp]
group_base = dc=zgtest,dc=local  # 部门的BaseDn
group_filter = (objectClass=posixGroup) # 部门的过滤规则
group_name_key = cn         # 部门的名称字段
group_id_key = gidNumber         # 部门的id字段

user_base = dc=zgtest,dc=local  # 用户的BaseDn
user_filter = (staffActive=1) # 用户的过滤规则
user_name_key = displayName     # 代表名称的字段
user_id_key = uidNumber         # 代表用户id的字段
user_mail_key = mail            # 代表用户邮箱的字段
user_mobile_key = mobile        # 代表用户手机的字段
user_group_key = gidNumber      # 代表用户所属部门id的字段
user_login_key = cn             # 代表用户登录用户名的字段
append_user_keys = staffAccess,staffActive,sn,givenName

[workcenter]
group_base = dc=zgtest,dc=local # 部门的BaseDn
group_filter = (objectClass=posixGroup) # 部门的过滤规则
group_name_key = cn
group_id_key = gidNumber

user_base = dc=zgtest,dc=local # 用户的BaseDn
user_filter = (staffActive=1) # 用户的过滤规则
user_name_key = displayName     # 代表名称的字段
user_id_key = uidNumber         # 代表用户id的字段
user_mail_key = mail            # 代表用户邮箱的字段
user_mobile_key = mobile        # 代表用户手机的字段
user_group_key = gidNumber      # 代表用户所属部门id的字段
user_login_key = cn             # 代表用户登录用户名的字段
append_user_keys = staffAccess,staffActive,sn,givenName   # 用户查询接口返回用户信息会附加这些字段

**Comment by w303972870** [comment]
不需要
